version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: products_global
    ports:
      - 27017:27017
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,aws
    ports:
      - "4566:4566"
    volumes:
      - ./docker/aws:/docker-entrypoint-initaws.d

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./docker/sql:/docker-entrypoint-initaws.d
